# Generated by Django 6.1 on 2026-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(upload_to='gallery/', verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Відео')], max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Медіафайл',
                'verbose_name_plural': 'Медіафайли',
                'ordering': ['-created_at'],
            },
        ),
    ]
