# Generated by Django 6.0.5 on 2026-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_create_default_survey'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_answer_per_question_in_response',
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question', 'choice'), name='unique_choice_per_question_in_response'),
        ),
    ]
